# Generated by Django 5.0.6 on 2024-06-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_theater', '0003_alter_post_author_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='title',
            field=models.TextField(default='Jurrasic Park'),
            preserve_default=False,
        ),
    ]
