# Generated by Django 5.0.6 on 2024-06-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_theater', '0006_choice_poll_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
