# Generated by Django 5.0.6 on 2024-06-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_theater', '0007_alter_poll_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
