# Generated by Django 5.0.6 on 2024-06-12 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_theater', '0008_alter_poll_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='choices',
        ),
        migrations.AddField(
            model_name='choice',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='app_theater.poll'),
        ),
    ]
