# Generated by Django 5.0.6 on 2024-06-13 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_theater', '0011_discussion_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment', to='app_theater.profile')),
                ('discussion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussion_comments', to='app_theater.profile')),
                ('likes', models.ManyToManyField(related_name='comment_likes', to='app_theater.profile')),
            ],
        ),
    ]
