# Generated by Django 5.0.6 on 2024-06-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_theater', '0014_menuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_minute', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('film', models.TextField()),
                ('date', models.DateField()),
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('times', models.ManyToManyField(related_name='showtime', to='app_theater.specifictime')),
            ],
        ),
    ]
