# Generated by Django 5.0.6 on 2024-06-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_theater', '0015_specifictime_showtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specifictime',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
