# Generated by Django 5.0.6 on 2024-07-05 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_theater', '0019_event_date_event_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread_comment', to='app_theater.profile')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_thread_comments', to='app_theater.comment')),
                ('likes', models.ManyToManyField(related_name='thread_comment_likes', to='app_theater.profile')),
            ],
        ),
    ]
